// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuw-mJS8L-YuqPANk7dDobZYP3HuKNuY',
    appId: '1:127599448717:web:621064b86667d8f4f248c4',
    messagingSenderId: '127599448717',
    projectId: 'the-leaderboard-ffb68',
    authDomain: 'the-leaderboard-ffb68.firebaseapp.com',
    storageBucket: 'the-leaderboard-ffb68.firebasestorage.app',
    measurementId: 'G-H14WZEK4B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40kJ-wsQsL44JRuqFOZmCdoN_TnogWEk',
    appId: '1:127599448717:android:42deb46ce3a9f2dcf248c4',
    messagingSenderId: '127599448717',
    projectId: 'the-leaderboard-ffb68',
    storageBucket: 'the-leaderboard-ffb68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhR5WUhHwEsUGKDt2NHIFmdlicjFpGuc',
    appId: '1:127599448717:ios:4e5f6ec3b026eb78f248c4',
    messagingSenderId: '127599448717',
    projectId: 'the-leaderboard-ffb68',
    storageBucket: 'the-leaderboard-ffb68.firebasestorage.app',
    iosBundleId: 'com.regamestudio.theleaderboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhR5WUhHwEsUGKDt2NHIFmdlicjFpGuc',
    appId: '1:127599448717:ios:50c1dea785a63cbef248c4',
    messagingSenderId: '127599448717',
    projectId: 'the-leaderboard-ffb68',
    storageBucket: 'the-leaderboard-ffb68.firebasestorage.app',
    iosBundleId: 'com.example.theLeaderboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbuw-mJS8L-YuqPANk7dDobZYP3HuKNuY',
    appId: '1:127599448717:web:9c2dfbe577ec96e5f248c4',
    messagingSenderId: '127599448717',
    projectId: 'the-leaderboard-ffb68',
    authDomain: 'the-leaderboard-ffb68.firebaseapp.com',
    storageBucket: 'the-leaderboard-ffb68.firebasestorage.app',
    measurementId: 'G-GHBQRRDK0B',
  );

}